import { Rubik_Dirt } from "next/font/google";
import "./globals.css";

const rubik = Rubik_Dirt({
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
      </body>
    </html>
  );
}
