import { Rubik_Dirt } from "next/font/google";
import Head from 'next/head';
import "./globals.css";
import Script from 'next/script'

const rubik = Rubik_Dirt({
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js" />
      <body className={rubik.className}>
        {children}
      </body>
    </html>
  );
}
